In [42]:
!pip install numpy

In [43]:
import numpy as np

In [44]:
# create a list of five integers
list_a = [1,2,4,5,6]

In [45]:
#convert the list to array using numpy
array_a = np.array(list_a)
print(array_a)

[1 2 4 5 6]


In [46]:
#print the type of list and array
print(type(list_a))
print(type(array_a))

<class 'list'>
<class 'numpy.ndarray'>


In [47]:
#print the shape of the array
print(array_a.shape)

(5,)


In [48]:
#append a string to the list
list_a.append("Shashwat")
print(list_a)

[1, 2, 4, 5, 6, 'Shashwat']


In [49]:
#convert the list into an array
array_b = np.array(list_a)
print(array_b)

['1' '2' '4' '5' '6' 'Shashwat']


In [50]:
print(type(array_b))

<class 'numpy.ndarray'>


In [51]:
#create another list and concatenate it with the previous list
list_b = [6,7,8,9,10]
list_c = list_a+list_b
print(list_c)

[1, 2, 4, 5, 6, 'Shashwat', 6, 7, 8, 9, 10]


In [52]:
#after concatenation, convert the list to array
array_c = np.array(list_c)
print(array_c)

['1' '2' '4' '5' '6' 'Shashwat' '6' '7' '8' '9' '10']


In [53]:
#create a list of list and convert it into an array
list_d = [[1,2], [3,4],[5,6]]
array_d = np.array(list_d)
print(array_d)

[[1 2]
 [3 4]
 [5 6]]


In [54]:
#after conversion, print the shape of the array
print(array_d.shape)

(3, 2)


In [55]:
#convert the array to float
array_d = array_d.astype(np.float32)
print(array_d)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [56]:
#convert the array again back to int 
array_d = array_d.astype(np.int32)
print(array_d)

[[1 2]
 [3 4]
 [5 6]]


In [57]:
#another way to convert the type is 
# newarray = np.array(oldarray, dtype="int") 

In [58]:
#NaN - Not a Number
#inf - infinity

In [59]:
0/1

0.0

In [60]:
-1/0

ZeroDivisionError: division by zero

In [61]:
1/-1

-1.0

In [62]:
100/33

3.0303030303030303

In [63]:
#create an integer array and convert it into float type
array_e = [[1,2,3], [4,5,6], [7,8,9]]
print(array_e)
array_e = np.array(array_e, dtype="float")
print(array_e)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [64]:
#replace some index values with NaN and inf
array_e[1,2] = np.NaN
array_e[2,2] = np.inf

print(array_e)

[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8. inf]]


In [67]:
#check if the array conatains any NaN or inf values
print(np.isnan(array_e))
print("")
print(np.isinf(array_e))

[[False False False]
 [False False  True]
 [False False False]]

[[False False False]
 [False False False]
 [False False  True]]


In [68]:
#checking both - nan and inf at the same time
flag = np.isnan(array_e)|np.isinf(array_e)
print(flag)

[[False False False]
 [False False  True]
 [False False  True]]


In [70]:
#replacing all the flag [true] values with 0 at a time
array_e[flag]=0
print(array_e)

[[1. 2. 3.]
 [4. 5. 0.]
 [7. 8. 0.]]


In [71]:
#print the mean value of the array
print(np.mean(array_e))

3.3333333333333335


In [73]:
#print the minimum value of the array
print(np.min(array_e))

0.0


In [74]:
#print the standard deviartion of the array
print(np.std(array_e))

2.7487370837451066


In [75]:
#print the variance value of the array
print(np.var(array_e))

7.555555555555554


In [78]:
#print the median value of the array
print(np.median(array_e))

3.0
